version: '3.6'

services:
  mailcatcher:
    image: 1001pharmadev/mailcatcher:latest
    labels:
    - SERVICE_1025_CHECK_TCP=true
    - SERVICE_1025_NAME=${COMPOSE_SERVICE_NAME}-mailcatcher-1025
    - SERVICE_1080_CHECK_HTTP=/
    - SERVICE_1080_NAME=${COMPOSE_SERVICE_NAME}-mailcatcher-1080
    - SERVICE_1080_TAGS=${MAILCATCHER_SERVICE_1080_TAGS}
    networks:
    - private
    - public
    ports:
    - 1025
    - 1080
    restart: always

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
