---
# file: defaults/main.yml

# enable rc.local script
hosts_enable_local: false

# run user specific rc functions on ssh connection
hosts_enable_rc: false

# Activate zram swap devices on host
hosts_enable_zram: false

# git repositories to clone
hosts_git_repositories: []
#  - { "repo": "ssh://git@github.com/aya/infra", "dest": "/src/infra" }

# list of rc functions to call at user connection
hosts_rc_functions:
    # customize PS1 variable
    - 01_custom_ps1
    # customize PROMPT variable
    # - 02_custom_prompt
    # launch a ssh agent and load all private keys located in ~/.ssh
    # - 03_ssh_agent
    # create and/or attach a tmux session
    # - 04_attach_tmux
    # create and/or attach a screen session
    - 05_attach_screen

# list of rc functions to cleanup (remove files)
# hosts_rc_cleanup:
#     - 03_ssh_agent
#     - 04_attach_tmux

# packages to install
hosts_packages: []

# packages specific to a distribution
hosts_packages_distro: []

# packages common to all distributions
hosts_packages_common:
  - { "name": "bash", "state": "present" }
  - { "name": "ca-certificates", "state": "present" }
  - { "name": "rsync", "state": "present" }
  - { "name": "screen", "state": "present" }
  - { "name": "tzdata", "state": "present" }

# a list of SSH private keys to copy
hosts_ssh_private_keys: []
# - ~/.ssh/id_rsa

# a list of public hosts keys to add to known_hosts
hosts_ssh_public_hosts_keys:
  - { "name": "github.com", "key": "files/etc/ssh/github.com.pub" }

# a list of github usernames to get public keys
hosts_ssh_users: []
# - aya

# a list of environment variables to write to user ~/.env
hosts_user_env: []
# - SHELL
