version: '3.6'

services:
  static:
    image: nginx:alpine
    command: /bin/sh -c "grep autoindex /etc/nginx/conf.d/default.conf >/dev/null 2>&1 || sed -i 's|index  index.html index.htm;|index  index.html index.htm;\n        autoindex on;|' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off"
    labels:
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-nginx-80
    - SERVICE_80_CHECK_TCP=true
    - SERVICE_80_CHECK_INITIAL_STATUS=passing
    - SERVICE_80_TAGS=${STATIC_SERVICE_80_TAGS}
    networks:
    - private
    - public
    ports:
    - 80
    restart: always
    volumes:
    - static:/usr/share/nginx/html:ro

volumes:
  static:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
