version: '3.6'

services:
  memcached:
    image: memcached:alpine
    labels:
    - SERVICE_11211_CHECK_TCP=true
    - SERVICE_11211_NAME=${COMPOSE_SERVICE_NAME}-memcached-11211
    networks:
    - private
    ports:
    - 11211
    restart: always

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
