version: '3.6'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.3
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_URL="http://elasticsearch:9200"
    labels:
    - SERVICE_5601_CHECK_HTTP=/app/kibana
    - SERVICE_5601_NAME=${COMPOSE_SERVICE_NAME}-kibana-5601
    - SERVICE_5601_TAGS=${KIBANA_SERVICE_5601_TAGS}
    networks:
    - private
    - public
    ports:
    - 5601
    restart: always

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
