version: '3.6'

services:
  cli:
    build:
      args:
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - UID=${UID}
      - USER=${USER}
      context: .
      dockerfile: docker/cli/Dockerfile
      target: ${DOCKER_BUILD_TARGET}
    command: tail -f /dev/null
    depends_on:
    - ssh
    environment:
    - SSH_AUTH_SOCK=/tmp/ssh-agent/socket
    image: ${DOCKER_REPO_INFRA}/${DOCKER_IMAGE_CLI}
    networks:
    - private
    restart: always
    volumes:
    - ssh:/tmp/ssh-agent:ro
    - ${MONOREPO_DIR}:${MONOREPO_DIR}:cached
    working_dir: ${MONOREPO_DIR}
  ssh:
    build:
      args:
      - UID=${UID}
      - USER=${USER}
      context: .
      dockerfile: docker/ssh/Dockerfile
      target: ${DOCKER_BUILD_TARGET}
    image: ${DOCKER_REPO_INFRA}/${DOCKER_IMAGE_SSH}
    networks:
    - private
    restart: always
    volumes:
    - ssh:/tmp/ssh-agent

volumes:
  ssh:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: uid=${UID}

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
