version: '3.6'

services:
  logagent:
    image: sematext/logagent:latest
    environment:
    - LOGAGENT_ARGS=-u 514 --docker /tmp/docker.sock --dockerEvents
    - LOGS_RECEIVER_URL=${ELASTICSEARCH_PROTOCOL}://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    - LOGS_TOKEN=logs
    networks:
    - private
    ports:
    - 514
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
