version: '3.6'

services:
  alertmanager:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/alertmanager
      - SLACK_WEBHOOK_ID=${SLACK_WEBHOOK_ID}
      context: ..
      dockerfile: docker/alertmanager/Dockerfile
    image: ${DOCKER_REPOSITORY}/alertmanager:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9093_NAME=${COMPOSE_SERVICE_NAME}-alertmanager-9093
    - SERVICE_9093_CHECK_TCP=true
    - SERVICE_9093_CHECK_INITIAL_STATUS=passing
    - SERVICE_9093_TAGS=${SERVICE_ALERTMANAGER_HTTP_TAGS}
    networks:
    - private
    - public
    ports:
    - 9093
    restart: always
  blackbox:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/blackbox
      context: ..
      dockerfile: docker/blackbox/Dockerfile
    image: ${DOCKER_REPOSITORY}/blackbox:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9115_NAME=${COMPOSE_SERVICE_NAME}-blackbox-9115
    - SERVICE_9115_CHECK_TCP=true
    - SERVICE_9115_CHECK_INITIAL_STATUS=passing
    - SERVICE_9115_TAGS=${SERVICE_BLACKBOX_HTTP_TAGS}
    networks:
    - private
    - public
    ports:
    - 9115
    restart: always
  es-exporter:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/es-exporter
      context: ..
      dockerfile: docker/es-exporter/Dockerfile
    command: -e 52.48.69.60:9200
    image: ${DOCKER_REPOSITORY}/es-exporter:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9206_NAME=${COMPOSE_SERVICE_NAME}-es-exporter-9206
    - SERVICE_9206_CHECK_TCP=true
    - SERVICE_9206_CHECK_INITIAL_STATUS=passing
    - SERVICE_9206_TAGS=${ES_EXPORTER_SERVICE_9206_TAGS}
    networks:
    - private
    - public
    ports:
    - 9206
    restart: always
  grafana:
    build:
      args:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - DOCKER_BUILD_DIR=docker/grafana
      - MYSQL_GRAFANA_USER=${MYSQL_GRAFANA_USER}
      - MYSQL_GRAFANA_PASSWORD=${MYSQL_GRAFANA_PASSWORD}
      - MYSQL_GRAFANA_DB=${MYSQL_GRAFANA_DB}
      context:  ..
      dockerfile: docker/grafana/Dockerfile
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    image: ${DOCKER_REPOSITORY}/grafana:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_3000_NAME=${COMPOSE_SERVICE_NAME}-grafana-3000
    - SERVICE_3000_CHECK_TCP=true
    - SERVICE_3000_CHECK_INITIAL_STATUS=passing
    - SERVICE_3000_TAGS=${SERVICE_GRAFANA_HTTP_TAGS}
    networks:
    - private
    - public
    ports:
    - 3000
    restart: always
    volumes:
    - grafana:/var/lib/grafana
  prometheus:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/prometheus
      - MONITORING_PRIMARY_TARGETS_BLACKBOX=${MONITORING_PRIMARY_TARGETS_BLACKBOX}
      - MONITORING_SECONDARY_TARGETS_BLACKBOX=${MONITORING_SECONDARY_TARGETS_BLACKBOX}
      context: ..
      dockerfile: docker/prometheus/Dockerfile
    image: ${DOCKER_REPOSITORY}/prometheus:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9090_NAME=${COMPOSE_SERVICE_NAME}-prometheus-9090
    - SERVICE_9090_CHECK_TCP=true
    - SERVICE_9090_CHECK_INITIAL_STATUS=passing
    - SERVICE_9090_TAGS=${SERVICE_PROMETHEUS_HTTP_TAGS}
    networks:
    - private
    - public
    ports:
    - 9090
    restart: always
    volumes:
    - prometheus:/prometheus

volumes:
  grafana:
  prometheus:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
