version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    labels:
    - SERVICE_4369_IGNORE=true
    - SERVICE_5671_IGNORE=true
    - SERVICE_5672_CHECK_TCP=true
    - SERVICE_5672_NAME=${COMPOSE_SERVICE_NAME}-rabbitmq-5672
    - SERVICE_15671_IGNORE=true
    - SERVICE_15672_CHECK_HTTP=/
    - SERVICE_15672_NAME=${COMPOSE_SERVICE_NAME}-rabbitmq-15672
    - SERVICE_15672_TAGS=${RABBITMQ_SERVICE_15672_TAGS}
    - SERVICE_25672_IGNORE=true
    networks:
    - private
    - public
    ports:
    - 5672
    - 15672
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
