version: '3.6'

services:
  nextcloud:
    image: nextcloud:17.0.2-apache
    environment:
    - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
    - MYSQL_HOST=${NEXTCLOUD_MYSQL_HOST}
    - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
    - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
    labels:
    - SERVICE_80_CHECK_TCP=true
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-nextcloud-80
    - SERVICE_80_TAGS=${NEXTCLOUD_SERVICE_80_TAGS}
    networks:
    - private
    - public
    ports:
    - 80
    volumes:
    - nextcloud:/var/www/html
    restart: always

volumes:
  nextcloud:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
  public:
    external: true
    name: node
