---
aws_cli_user: "{{ ansible_user|default('root') }}"
aws_cli_group: "{{ ansible_user|default('root') }}"
aws_output_format: 'json'
aws_region: 'eu-west-1'
aws_access_key_id: 'YOUR_ACCESS_KEY_ID'
aws_secret_access_key: 'YOUR_SECRET_ACCESS_KEY'
