version: '3.6'

services:
  mysql:
    build:
      context: ../
      dockerfile: mysql/mysql/Dockerfile
    image: ${DOCKER_REPOSITORY}/mysql:${DOCKER_IMAGE_TAG}
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
    - SERVICE_CHECK_SCRIPT=container-check-status $$SERVICE_IP
    - SERVICE_3306_NAME=${COMPOSE_SERVICE_NAME}-mysql-3306
    networks:
    - private
    ports:
    - 3306
    volumes:
    - mysql:/var/lib/mysql
    restart: always

volumes:
  mysql:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
