#!/bin/bash
# https://github.com/hashicorp/consul/issues/3182

if [ $# -ne 1 ]; then
    >&2 echo "Invalid parameters: '$@'"
    echo "USAGE: check-container-status <container-id|container-name|container-ip>"
    exit 2
fi

CONTAINER_ID="$1"
CONTAINER_STATUS=$(docker inspect -f '{{.Id}} {{.Name}} {{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}} {{.State.Health.Status}}' $(docker ps -q) 2>/dev/null |awk '/\<'${CONTAINER_ID}'\>/ {print $NF}')

echo ${CONTAINER_STATUS}

if [ "${CONTAINER_STATUS}" = "healthy" ]; then
    exit 0
fi

if [ "${CONTAINER_STATUS}" = "starting" ]; then
    exit 1
fi

exit 2
