version: '3.6'

services:
  drone-gc:
    image: drone/gc:latest
    environment:
    # - GC_DEBUG=true
    # - GC_DEBUG_COLOR=true
    # - GC_DEBUG_PRETTY=true
    - GC_CACHE=20gb
    - GC_INTERVAL=5m
    networks:
    - private
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  private:
      external: true
      name: ${DOCKER_NETWORK_PRIVATE}
