version: '3.6'

services:
  redmine:
    image: sameersbn/redmine:4.0.4
    # command: /bin/sh -c "crontab -l |sed 's|@hourly|@hourly cd /home/redmine/data/files/1001Pharmacies \&\& git fetch -q --all -p \&\&|' |crontab"
    environment:
    - DB_ADAPTER=mysql2
    - DB_HOST=${REDMINE_DB_HOST}
    - DB_NAME=${REDMINE_DB_NAME}
    - DB_USER=${REDMINE_DB_USER}
    - DB_PASS=${REDMINE_DB_PASS}
    - REDMINE_SECRET_TOKEN=${REDMINE_REDMINE_SECRET_TOKEN}
    - SMTP_DOMAIN=${REDMINE_SMTP_DOMAIN}
    - SMTP_USER=${REDMINE_SMTP_USER}
    - SMTP_PASS=${REDMINE_SMTP_PASS}
    - TZ=Europe/Paris
    labels:
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-redmine-80
    - SERVICE_80_CHECK_TCP=true
    - SERVICE_80_CHECK_INITIAL_STATUS=passing
    - SERVICE_80_TAGS=${REDMINE_SERVICE_80_TAGS}
    - SERVICE_443_IGNORE=true
    networks:
    - private
    ports:
    - 80
    restart: always
    volumes:
    - redmine:/home/redmine/data
  redmine3:
    image: sameersbn/redmine:3.4.11
    # command: /bin/sh -c "crontab -l |sed 's|@hourly|@hourly cd /home/redmine/data/files/1001Pharmacies \&\& git fetch -q --all -p \&\&|' |crontab"
    environment:
    - DB_ADAPTER=mysql2
    - DB_HOST=${REDMINE3_DB_HOST}
    - DB_NAME=${REDMINE3_DB_NAME}
    - DB_USER=${REDMINE3_DB_USER}
    - DB_PASS=${REDMINE3_DB_PASS}
    - REDMINE_SECRET_TOKEN=${REDMINE3_REDMINE_SECRET_TOKEN}
    - SMTP_DOMAIN=${REDMINE3_SMTP_DOMAIN}
    - SMTP_USER=${REDMINE3_SMTP_USER}
    - SMTP_PASS=${REDMINE3_SMTP_PASS}
    - TZ=Europe/Paris
    labels:
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-redmine3-80
    - SERVICE_80_CHECK_TCP=true
    - SERVICE_80_CHECK_INITIAL_STATUS=passing
    - SERVICE_80_TAGS=${REDMINE3_SERVICE_80_TAGS}
    - SERVICE_443_IGNORE=true
    networks:
    - private
    ports:
    - 80
    restart: always
    volumes:
    - redmine3:/home/redmine/data
  static:
    image: nginx:alpine
    command: /bin/sh -c "grep autoindex /etc/nginx/conf.d/default.conf >/dev/null 2>&1 || sed -i 's|index  index.html index.htm;|index  index.html index.htm;\n        autoindex on;|' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    labels:
    - SERVICE_80_NAME=${COMPOSE_SERVICE_NAME}-static-80
    - SERVICE_80_CHECK_TCP=true
    - SERVICE_80_CHECK_INITIAL_STATUS=passing
    - SERVICE_80_TAGS=${STATIC_SERVICE_80_TAGS}
    networks:
    - private
    ports:
    - 80
    restart: always
    volumes:
    - static:/usr/share/nginx/html:ro

volumes:
  redmine:
  redmine3:
  static:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK}
